volumes:
  db:
  nextcloud:

services:
  app:
    image: nextcloud
    restart: always
    ports:
      - 9080:80
      - 9433:433
    depends_on:
      - db
      - proxy
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.aniketprajapati.me
      - OBJECTSTORE_S3_REGION=${S3_REGION}
      - OBJECTSTORE_S3_KEY=${AWS_ACCESS_KEY_ID}
      - OBJECTSTORE_S3_SECRET=${AWS_SECRET_ACCESS_KEY}
      - OBJECTSTORE_S3_BUCKET=${S3_BUCKET}
    volumes:
      - nextcloud:/var/www/html/

  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data

  pg_backup_s3:
    build: postgres-backup-s3
    environment:
      SCHEDULE: ${PG_BACKUP_SCHEDULE}
      PASSPHRASE: ${POSTGRES_PASSWORD}
      S3_REGION: ${S3_REGION}
      S3_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3_BUCKET: ${S3_BUCKET}
      S3_PREFIX: ${S3_PREFIX}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DATABASE: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      
  proxy:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 433:433
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log
